// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "Infocontrol_whitewoods_Year3Interfaces.generated.h"


/** UNINTERFACE generated from Articy Basic Character Properties Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="Infocontrol_whitewoods_Year3 Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UInfocontrol_whitewoods_Year3ObjectWithDefaultBasicCharacterFeatureFeature : public UInterface { GENERATED_BODY() };
class IInfocontrol_whitewoods_Year3ObjectWithDefaultBasicCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UInfocontrol_whitewoods_Year3DefaultBasicCharacterFeatureFeature* GetFeatureDefaultBasicCharacterFeature() const
	{
		return nullptr;
	}
};

/** UNINTERFACE generated from Articy Extended Character Properties Feature */
UINTERFACE(MinimalAPI, BlueprintType, Category="Infocontrol_whitewoods_Year3 Feature Interfaces", meta=(CannotImplementInterfaceInBlueprint))
class UInfocontrol_whitewoods_Year3ObjectWithDefaultExtendedCharacterFeatureFeature : public UInterface { GENERATED_BODY() };
class IInfocontrol_whitewoods_Year3ObjectWithDefaultExtendedCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	UFUNCTION(BlueprintCallable)
	virtual class UInfocontrol_whitewoods_Year3DefaultExtendedCharacterFeatureFeature* GetFeatureDefaultExtendedCharacterFeature() const
	{
		return nullptr;
	}
};
