// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyDatabase.h"
#include "Infocontrol_whitewoods_Year3ExpressoScripts.h"
#include "Infocontrol_whitewoods_Year3Database.generated.h"

UCLASS(BlueprintType)
class PROJECTWHITEWOOD_API UInfocontrol_whitewoods_Year3Database : public UArticyDatabase
{
	GENERATED_BODY()
	
public:
	
	/** Get the instance (copy of the asset) of the database. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyDB", keywords="database"))
	static UInfocontrol_whitewoods_Year3Database* Get(const UObject* WorldContext) 
	{
		return static_cast<UInfocontrol_whitewoods_Year3Database*>(Super::Get(WorldContext));
	}
	
	/** Get the global variables. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UInfocontrol_whitewoods_Year3GlobalVariables* GetGVs() const override
	{
		return static_cast<UInfocontrol_whitewoods_Year3GlobalVariables*>(Super::GetGVs());
	}
	/** Gets the current runtime instance of a set of GVs. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UInfocontrol_whitewoods_Year3GlobalVariables* GetRuntimeGVs(UArticyAlternativeGlobalVariables* Asset) const override
	{
		return static_cast<UInfocontrol_whitewoods_Year3GlobalVariables*>(Super::GetRuntimeGVs(Asset));
	}
};
