// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyTypeSystem.h"
#include "Infocontrol_whitewoods_Year3TypeSystem.generated.h"

/** Articy Type System */
UCLASS(BlueprintType)
class PROJECTWHITEWOOD_API UInfocontrol_whitewoods_Year3TypeSystem : public UArticyTypeSystem
{
	GENERATED_BODY()
	
};
