// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyGlobalVariables.h"
#include "Infocontrol_whitewoods_Year3GlobalVariables.generated.h"
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(push)
#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
#endif

/** Global Articy Variables */
UCLASS(BlueprintType)
class PROJECTWHITEWOOD_API UInfocontrol_whitewoods_Year3GlobalVariables : public UArticyGlobalVariables
{
	GENERATED_BODY()
	
public:
	
	 UInfocontrol_whitewoods_Year3GlobalVariables() 
	{
		/** create the namespaces */
		
		Init();
	}
	
	void Init() 
	{
		/** initialize the namespaces */
	}
	
	/** Get the default GlobalVariables (a copy of the asset). */
	UFUNCTION(BlueprintPure, Category="ArticyGlobalVariables", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyGV", keywords="global variables"))
	static UInfocontrol_whitewoods_Year3GlobalVariables* GetDefault(const UObject* WorldContext) 
	{
		return static_cast<UInfocontrol_whitewoods_Year3GlobalVariables*>(UArticyGlobalVariables::GetDefault(WorldContext));
	}
};
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(pop)
#endif
